### PR TITLE
Fix bug where running change identifiers did not work

### PR DESCRIPTION
**Pull request by munnja001**
Because the admin module has change, running the change-identifiers ant task would fail. Removing these lines allows it to run properly again

### CODE REVIEW

**Comment by bpolster** [comment]
@apazzolini or @phillipuniverse - Please review and accept or reject this.

**Comment by watermelonjuice** [comment]
Its a bad merge. Some lines get readded in a later commit. Unmerge this one and I'll create a new pull request based on the current codebase.

**Comment by phillipuniverse** [comment]
@watermelonjuice made the same fix on the BroadleafCommerce-3.0.x and merged into develop. Tested there and it appears that it now changes the names correctly on both with no errors.

Let me know if you still see something amiss.

**Comment by watermelonjuice** [comment]
It's good now.

**Pull request merged**
