### PR TITLE
#169 - modified update account to require a password field

### PR DESCRIPTION
**Pull request by ncrum**

### CODE REVIEW

**Comment by ncrum** [comment]
Referencing BroadleafCommerce/QA#616

**Comment by jefffischer** [comment]
This should reference the 4.0 branch. Also, your commit message should be more descriptive what problem is being fixed.

**Comment by ncrum** [comment]
@jefffischer will do on the commit message, however, which is the 4.0 branch on DemoSite? I don't see one.

**Comment by jefffischer** [comment]
@ncrum Sorry - you're correct. I was thinking demosite private. It looks like you had the right branch.

**Pull request closed without merging**
