### PR TITLE
fix combined/pom.xml processing in ant task

### PR DESCRIPTION
**Pull request by c0nscience**
only the 'mycompany' token was replaced in combined/pom.xml which produced maven errors ... so fixed this to search for 'com.mycompany' token and replace it with the maven-module variable

### CODE REVIEW

**Comment by jefffischer** [comment]
Cool - We'll make sure this get's into the right spot. Fyi - we need to update master, but if you're looking to work with the demo, I would highly suggest basing your project off the current develop branch instead of master.

**Comment by c0nscience** [comment]
Ok thanks for the hint :)

**Comment by c0nscience** [comment]
hmm it seems a bit harder to start with the dev branche, because I had no access to the 2.2.0-SNAPSHOT versions, so there are many classes missing ... is the master branch so out dated ?

**Comment by c0nscience** [comment]
oh no sorry it was my fault ... I thought that I can't use the snapshot version, but it works :D cool :thumbsup: 
but how stable is the 2.2.0-SNAPSHOT version ? ^^

**Comment by jefffischer** [comment]
It's very stable. It will probably go GA tomorrow.

**Comment by c0nscience** [comment]
awesome, now I could start with my project ... thanks for the demo site project :)

**Comment by phillipuniverse** [comment]
We have removed the combined module for now perhaps to bring back in the future.

**Pull request closed without merging**
