### PR TITLE
Update Jetty plugin to 9.2.6

### PR DESCRIPTION
**Pull request by firen**
Please check my modification for nicer IntelliJ IDEA integration with new jetty-maven-plugin.
Maybe you will find it useful.

### CODE REVIEW

**Comment by phillipuniverse** [comment]
This looks pretty good at first glance. Curious why you changed the templates to be absolute paths (adding the slash at the beginning)?

**Comment by firen** [comment]
You mean I did another way around :)? I have removed the slashes at the beginning.
I did it so because apparently Jetty 9 is unable to resolve templates with paths /WEB-INF/templates//layout/partial/head.html (please notice double slash). You will get an exception saying Thymeleaf is not able to resolve template for example /layout/partial/head.
You can put breakpoint in ServletContextResourceResolver:87 to check that behavior.
Unfortunatly, I was not able figure out why Jetty 9 behaves in such a way.

If any doubts, please ask.

**Comment by phillipuniverse** [comment]
@firen gotcha, I understand.

We try to not accept pull requests into the master branch. Would you mind re-opening this pull request but changing it to instead target the `BroadleafCommerce-3.1.x` branch?

Thanks again for your work, I would like to get this merged in sometime this week.

**Comment by phillipuniverse** [comment]
A few notes on this that I wanted to capture after pulling this down locally and playing with it:
1. This basically eliminates any need for ant which, in general, is a good thing but means that we should apply this to 3.1 as I originally thought. Any changes like this should be in the next Broadleaf major release as it implies changing things like the Getting Started docs, etc
2. If I had to choose, would rather have the embedded Tomcat plugin configured vs the Jetty plugin since most of the people that use Broadleaf are deploying on Tomcat in production
3. If we are going to keep this embedded Jetty plugin then we should decide if this is going to be in addition to Tomcat or remove it altogether. I am leaning towards removing the Jetty plugin completely just in terms of simplicitly.

Going to think about this more but this is the best place to use as the starting point if we were to keep around Jetty. Nice work!

**Comment by firen** [comment]
Glad I could help. Cheers.

**Pull request closed without merging**
