### PR TITLE
Adds ISO countries

### PR DESCRIPTION
**Pull request by watermelonjuice**

### CODE REVIEW

**Comment by bpolster** [comment]
Please do not merge this until we have discussed internally.   @watermelonjuice this can easily be done in your specific project until we have made a decision on this.   

At current, my opinion is that we should provide alternate data load scripts but not by default load all countries.   Most of the implementations we see are for specific geographies.

Regardless, this is worth further discussion.

**Comment by watermelonjuice** [comment]
Ok. As is, anyone who would want to use DemoSite with i18n Paypal checkout would require customization.

**Comment by watermelonjuice** [comment]
I've amended the commit to include some additional states.

**Comment by phillipuniverse** [comment]
I am going to merge this in but then split this into its own file that can be loaded separately. Not going to load all of these in by default.

**Pull request merged**
